# cloudbuild.yaml

options:
  # Send logs only to Cloud Logging (no GCS bucket needed)
  logging: CLOUD_LOGGING_ONLY

substitutions:
  # Define a custom IMAGE variable that tags with the short git SHA
  _IMAGE: "gcr.io/$PROJECT_ID/cj-export:${SHORT_SHA}"

steps:
  # 1) Build & publish container with Buildpacks
  - name: "gcr.io/buildpacks/builder"
    args:
      - "--path=."
      - "--publish"
      - "--tag=${_IMAGE}"

  # 2) Deploy that image to Cloud Run
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: "gcloud"
    args:
      - "run"
      - "deploy"
      - "cj-to-sheets"
      - "--region=europe-north2"
      - "--platform=managed"
      - "--image=${_IMAGE}"
      - "--allow-unauthenticated"
