# cloudbuild.yaml

options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  # Use the built-in PROJECT_ID and SHORT_SHA substitutions
  _IMAGE: "gcr.io/${PROJECT_ID}/cj-export:${SHORT_SHA}"

steps:
  # 1) Build & publish container via Buildpacks
  - name: "gcr.io/buildpacks/builder"
    args:
      - "--path=."
      - "--publish"
      - "--tag=${_IMAGE}"

  # 2) Deploy that published image to Cloud Run
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: "gcloud"
    args:
      - "run"
      - "deploy"
      - "cj-to-sheets"
      - "--region=europe-north2"
      - "--platform=managed"
      - "--image=${_IMAGE}"
      - "--allow-unauthenticated"

# Expose the image for potential downstream steps (optional)
images:
  - "${_IMAGE}"
